### ISSUE TITLE
BaseURLNotSetError: connection timed out

### ISSUE THREAD

**Issue by sandeep-tz** [chadxz/imap-simple#13]
While we are using the package to open inbox, and read Last Unseen Emails. It works for most part of the time. But sometimes in between we are getting this error:

 BaseURLNotSetError: connection timed out. timeout = 3000 ms
    at Connection.imapOnError (/home/ubuntu/<project name>/web/node_modules/imap-simple/lib/imapSimple.js:360:23)
    at Connection.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at null._onTimeout (/home/ubuntu/<project name>/web/node_modules/imap-simple/node_modules/imap/lib/Connection.js:140:12)
    at Timer.listOnTimeout (timers.js:92:15)

There is no specific scenario. 

Can anyone please throw some details about it?

Thanks

**Comment by chadxz** [comment]
It means that the library timed out while trying to authenticate with the email provider. The name "BaseURLNotSetError" was a typo and has been fixed in 3.0.0. Sorry for any confusion.
